project.a_OBJS = 																\
	$(MODULES)/BitArray/bitArray.o 										\
	$(MODULES)/RBTree/RBTree.o 											\
	$(MODULES)/HashTable/HashTable.o 										\
	$(MODULES)/List/list.o  											\
	$(MODULES)/DisJointSet/DisJointSet.o 									
	

include ../common.mk	
