project.a_OBJS = 																\
	$(MODULES)/BitArray/bitArray.o 										\
	$(MODULES)/RBTree/RBTree.o 											\
	$(MODULES)/HashTable/HashTable.o 										\
	$(MODULES)/List/list.o  											\
	$(MODULES)/DisJointSet/DisJointSet.o 								 	\
	$(MODULES)/JobScheduler/JobScheduler.o 								\
	$(MODULES)/Queue/Queue.o 											\
	$(MODULES)/LogisticRegression/LogisticRegression.o 					\
	$(MODULES)/Dataset/Dataset.o 					

	

include ../common.mk	
