name: run-tests
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1

    - name: make run
      run: make run CFLAGS=-fPIC

    - name: make valgrind
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt install valgrind
        make valgrind CFLAGS=-fPIC
    - name: Upload
      if: startsWith(github.event.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v2
      with:
        name: compiled-${{ matrix.os }}
        path: .
